default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  host: localhost
  database: dev
  username: dev
  password: dev
  port: 5437
  <<: *default

test:
  host: localhost
  database: test
  username: dev
  password: dev
  port: 5437
  <<: *default

production:
  <<: *default
  database: dms_reports_production
  username: dms_reports
  password: <%= ENV["DMS_REPORTS_DATABASE_PASSWORD"] %>
